FROM node:16

# Configurar el directorio de trabajo
WORKDIR /usr/src/app

# Copiar el código fuente
COPY . .

# Instalar dependencias
RUN npm install

# Exponer el puerto
EXPOSE 3000

# Comando para iniciar el servidor
CMD ["npm", "run", "dev"]