
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: proyecto-gestion-backend
    container_name: backend
    ports:
      - "8000:8000"
      - "5173:5173"  # Puerto de desarrollo de Vite
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=your_database_name
      - DB_USERNAME=your_username
      - DB_PASSWORD=your_password
    volumes:
      - .:/var/www/html
      - backend-vendor:/var/www/html/vendor  # Volumen para preservar vendor
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_DB=your_database_name
      - POSTGRES_USER=your_username
      - POSTGRES_PASSWORD=your_password
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
  backend-vendor:  # Volumen para el vendor de PHP